import { NextRequest } from "next/server";
import fs from "fs";
import path from "path";

const SCRIP_MAP_PATH = path.join(process.cwd(), "data", "breeze-scrip-map.json");

// ── NIFTY 500 priority set ─────────────────────────────────────────────────────
// These rank above the rest of the universe in autocomplete results.
const NIFTY500: ReadonlySet<string> = new Set([
  // NIFTY 50
  "ADANIENT","ADANIPORTS","APOLLOHOSP","ASIANPAINT","AXISBANK","BAJAJ-AUTO",
  "BAJAJFINSV","BAJFINANCE","BHARTIARTL","BPCL","BRITANNIA","CIPLA","COALINDIA",
  "DIVISLAB","DRREDDY","EICHERMOT","ETERNAL","GRASIM","HCLTECH","HDFCBANK",
  "HDFCLIFE","HEROMOTOCO","HINDALCO","HINDUNILVR","ICICIBANK","INDUSINDBK",
  "INFY","ITC","JIOFIN","JSWSTEEL","KOTAKBANK","LT","M&M","MARUTI","NESTLEIND",
  "NTPC","ONGC","POWERGRID","RELIANCE","SBILIFE","SBIN","SHRIRAMFIN","SUNPHARMA",
  "TATACONSUM","TATAMOTORS","TATASTEEL","TCS","TECHM","TITAN","ULTRACEMCO","WIPRO",
  // NIFTY Next 50
  "ADANIGREEN","AMBUJACEM","AUROPHARMA","BANDHANBNK","BERGEPAINT","BIOCON",
  "BOSCHLTD","CANBK","CHOLAFIN","COLPAL","CONCOR","DABUR","DLF","FEDERALBNK",
  "GAIL","GODREJCP","GODREJPROP","HAVELLS","ICICIPRULI","IDFCFIRSTB","INDUSTOWER",
  "IRCTC","LUPIN","MPHASIS","NAUKRI","NHPC","NMDC","OFSS","PAGEIND","PIDILITIND",
  "PNB","RECLTD","SAIL","SIEMENS","SRF","TORNTPHARM","TRENT","TVSMOTOR","UBL",
  "VEDL","VOLTAS","ZOMATO","INDIGO","BEL","HDFCAMC","MCDOWELL-N","OBEROIRLTY",
  "PGHH","ABB",
  // NIFTY Midcap 150 (well-known)
  "AAPL","ACC","ABCAPITAL","ABFRL","ALKEM","APLLTD","ASHOKLEY","ASTRAL",
  "ATUL","AUBANK","BALKRISIND","BATAINDIA","BHARATFORG","BHEL","BRIGADE",
  "CAMS","CANFINHOME","CARBORUNIV","CASTROLIND","CEATLTD","CENTRALBK",
  "CGPOWER","CHAMBLFERT","COFORGE","CROMPTON","CUMMINSIND","CYIENT",
  "DATAMATICS","DCMSHRIRAM","DEEPAKFERT","DEEPAKNTR","DELTACORP","DELHIVERY",
  "DIXON","EIDPARRY","ELGIEQUIP","EMAMILTD","ENGINERSIN","ESCORTS",
  "EXIDEIND","FACT","FLUOROCHEM","FORTIS","GLENMARK","GNFC","GODREJIND",
  "GRANULES","GSPL","GUJGASLTD","HAPPSTMNDS","HFCL","HINDZINC","HUDCO",
  "IBREALEST","IDFC","IEINDIA","IIFL","INDIANB","INDIAMART","INDIACEM",
  "INDHOTEL","INTELLECT","IOB","IPCALAB","IRB","IRFC","JBCHEPHARM",
  "JKCEMENT","JKLAKSHMI","JKPAPER","JPPOWER","JSL","JUBLFOOD","JUBLINGREA",
  "KAJARIACER","KALPATPOWR","KANSAINER","KARURVYSYA","KEC","KMARTRES",
  "KNRCON","KPIL","KRISHANA","LALPATHLAB","LAURUSLABS","LICHSGFIN",
  "LINDEINDIA","LTFH","LTTS","LUXIND","MAHINDCIE","MAITHANALL","MANAPPURAM",
  "MARICO","MAXHEALTH","MCX","METROPOLIS","MFSL","MHRIL","MINDAIND",
  "MINDTREE","MISHRA","MRF","MRPL","NATIONALUM","NAVINFLUOR","NAUKRI",
  "NBCC","NCC","NIACL","NLCINDIA","NOCIL","NUVOCO","OIL","OLECTRA",
  "ORIENTELEC","PCBL","PERSISTENT","PETRONET","PFIZER","PHOENIXLTD",
  "POLYCAB","POLYMED","POWERMECH","PRAJIND","PRESTIGE","PRINCEPIPE",
  "RADICO","RAIN","RAMCOCEM","RATNAMANI","RAYMOND","REDINGTON","RELAXO",
  "RITES","ROUTE","RPOWER","SAFARI","SANOFI","SCHAEFFLER","SEQUENT",
  "SKFINDIA","SOBHA","SOLARINDS","SONATSOFTW","STARCEMENT","STLTECH",
  "SUMICHEM","SUNTV","SUPREMEIND","SUVENPHAR","SUZLON","SYNGENE",
  "TANLA","TATACOMM","TATACHEM","TATAELXSI","TATAINVEST","TATAPOWER",
  "TCNSBRANDS","TEAMLEASE","THERMAX","THYROCARE","TIINDIA","TIMKEN",
  "TORNTPOWER","TTKPRESTIG","TVSHLTD","UCOBANK","UJJIVANSFB","UNIONBANK",
  "UNOMINDA","UPL","UTIAMC","VAIBHAVGBL","VARDHACRLC","VARROC","VEDL",
  "VENKEYS","VGUARD","VHL","VIJAYABANK","VINATIORGA","VIPIND","VMART",
  "VODAIDEA","VSTIND","WABCOINDIA","WELCORP","WELSPUNIND","WESTLIFE",
  "WHIRLPOOL","WIPRO","WOCKPHARMA","XCHANGING","YESBANK","ZEEL","ZENSARTECH",
  "ZENTEC","ZFCVINDIA","ZOMATO","ZYDUSLIFE","ZYDUSWELL",
  // Additional large-caps frequently searched
  "ADANIPOWER","ADANITRANS","ALEMBICLTD","ALEMBICPH","AMBER","ANGELONE",
  "APLAPOLLO","APTUS","ARVINDFASN","ATUL","BAJAJHLDNG","BALKRISIND",
  "BALRAMCHIN","BANKBARODA","BATA","BAYERCROP","BEML","BSOFT","CANBK",
  "CDSL","CENTURYTEX","CERA","CHALET","CRAFTSMAN","CUB","DALBHARAT",
  "DBCORP","DHANUKA","EDELWEISS","EPL","EQUITASBNK","ERIS","ESABINDIA",
  "EUROBOND","FIEMIND","FINPIPE","FIVESTAR","FLUOROCHEM","FMGOETZE",
  "FSL","GICRE","GILLETTE","GLAXO","GLS","GMRINFRA","GNFC",
  "GODFRYPHLP","GPPL","GREENPANEL","GRINDWELL","GRSE","GULFOILLUB",
  "HARDWYN","HEIDELBERG","HLEGLAS","HMT","HOMEFIRST","HONAUT","HPL",
  "HSIL","IDFCFIRSTB","IFBIND","IGARASHI","IITL","IMAGICAA","IMFA",
  "INDIGOPNTS","INDOSTAR","INDOWIND","INFOSONICS","INGERRAND",
  "INOXGREEN","INOXWIND","IOC","IOCL","IPCA","JBMA","JETAIRWAYS",
  "JINDALSAW","JINDALPOLY","JINDALSTEEL","JINDALWSAW","JMFINANCIAL",
  "JNKL","JPINFRA","JSWENERGY","JSWHL","JTEKTINDIA","JUNIPERHOTEL",
  "JUSTDIAL","JYOTHYLAB","KFINTECH","KHADIM","KITEX","KTKBANK",
  "KUVEMPU","LEMONTREE","LTIM","MAHABANK","MAHLOG","MANKIND","MASFIN",
  "MATRIMONY","MAWANASUG","MAZAGON","MEDPLUS","METROBRAND","MGHL",
  "MIDHANI","MINDACORP","MOLDTECH","MOTHERSON","MSTCLTD","MUTHOOTFIN",
  "NATCOPHARM","NAVNETEDUL","NESCO","NETWORK18","NEWGEN","NEWJAISA",
  "NIITLTD","NILKAMAL","NIRAJ","NMSLTD","NRL","NSLNISP","OILCOUNTUB",
  "ONEPOINT","ONMOBILE","OPTOCIRCUI","ORCHIDPHAR","ORIENTCEM",
  "ORIENTPPR","PANAMAPET","PARADEEP","PARAS","PATANJALI","PATELENG",
  "PATIL","PBAINFRA","PCJEWELLER","PDMJEPAPER","PFIZER","PGHL",
  "PILANIINVS","PIONEEREMB","PNBGILTS","PNBHOUSING","POKARNA",
  "POLSONS","POLYMED","PONDINDS","POWEINDIA","POWERINDIA","PRAJIND",
  "PREMIER","PRIMADENTA","PSB","PSPPROJECT","PUNJLLOYD","PURVA",
  "QUESS","QUICKHEAL","RAJRATAN","RAMCOSYS","RATNAMANI","RBLBANK",
  "RCOM","RCF","RELIGARE","REMSONS","RENUKA","REPCOHOME","RESPONIND",
  "RFCL","RHFL","RINFRA","RITEINDIA","RKDL","ROHITFERRO","ROLL",
  "RSWM","RTNINDIA","RUBYMILLS","RUCHI","RUSHIL","S","SAGAR",
  "SAGARDEEP","SAICHEM","SAKHTISUG","SALSTEEL","SAMBHAAVNA",
  "SANOFI","SANWARIA","SARDAEN","SAREGAMA","SARLAPOLY","SBICARD",
  "SBICARDS","SCHAEFFLER","SEPC","SERVOTECH","SESAGOA","SFCL",
  "SFL","SHANKARA","SHANTIGEAR","SHARDACROP","SHASUN","SHILPAMED",
  "SHOPERSTOP","SHREEPUSHK","SHRIRAMCIT","SHTF","SIGACHI",
  "SIGNATUREG","SILGO","SIMPLEXINF","SIRCA","SKIL","SKIPPER",
  "SMCGLOBAL","SNOWMAN","SOBHA","SOLARA","SOUTHBANK","SPAL",
  "SPANDANA","SPARC","SPCENET","SPECTRANET","SPENCERS","SREINFRA",
  "SRTRANSFIN","STAR","STARTECK","STCINDIA","STEELCITY","STERLITE",
  "STLTECH","STOVEC","SUBROS","SUDARSCHEM","SUKHJITS","SUMICHEM",
  "SUNDARMFIN","SUNDRAMBRAK","SUNDRMFAST","SUNFLAG","SUNPHARMA",
  "SURAJEST","SURANI","SURYAROSNI","SUVEN","SUVENPHAR","SVBL",
  "SWANENERGY","SWSOLAR","SYMPHONY","SYNCHRONY","SYNCOMF",
]);

// In-memory cache so we only parse the file once per server lifetime
let _cachedSymbols: string[] | null = null;

function getEquitySymbols(): string[] {
  if (_cachedSymbols) return _cachedSymbols;
  try {
    const raw = fs.readFileSync(SCRIP_MAP_PATH, "utf-8");
    const data = JSON.parse(raw) as { map: Record<string, string> };
    // NSE equity symbols are purely alphabetic (plus & and -).
    // Reject anything containing a digit — those are bonds/G-sec codes.
    _cachedSymbols = Object.keys(data.map)
      .filter(k => /^[A-Z][A-Z&\-]{0,18}[A-Z]$/.test(k) || /^[A-Z]{2,4}$/.test(k))
      .sort();
    return _cachedSymbols;
  } catch {
    return [];
  }
}

export const dynamic = "force-dynamic";

export async function GET(req: NextRequest) {
  const q = (req.nextUrl.searchParams.get("q") ?? "").toUpperCase().trim();
  if (!q) return Response.json({ symbols: [] });

  const all = getEquitySymbols();

  // Rank: NIFTY500 prefix → other prefix → NIFTY500 contains → other contains
  const n500PrefixMatches  = all.filter(s => s.startsWith(q) && NIFTY500.has(s));
  const otherPrefixMatches = all.filter(s => s.startsWith(q) && !NIFTY500.has(s));
  const n500ContainMatches = all.filter(s => !s.startsWith(q) && s.includes(q) && NIFTY500.has(s));
  const otherContainMatches = all.filter(s => !s.startsWith(q) && s.includes(q) && !NIFTY500.has(s));

  const results = [
    ...n500PrefixMatches,
    ...otherPrefixMatches,
    ...n500ContainMatches,
    ...otherContainMatches,
  ].slice(0, 10);

  return Response.json({ symbols: results });
}
